# yazi.toml
[mgr]
show_hidden = true

[opener]
edit = [{ run = 'nvim "$@"', desc = "Edit with Neovim", block = true }]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { mime = "application/json", use = "edit" },
  { name = "*", use = "edit" },
]

[preview]
rules = [
  { mime = "text/*", run = "~/.config/yazi/plugins/bat-preview.sh {file}" },
  { mime = "application/json", run = "~/.config/yazi/plugins/bat-preview.sh {file}" },
]
